/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Estado.Estado;
import Resources.EfectoDeSonido;
import java.util.ArrayList;
import EstellarG.Dorothy;
import EstellarG.Katherin;
import EstellarG.Mary;
import java.awt.CardLayout;

/**
 *
 * @author Camilo Cespedes
 */
public class Lienzo extends javax.swing.JPanel {

    ArrayList<EfectoDeSonido> efectos;
    VentanaDesarrollo frame;
    Mary mary;
    Katherin katherin;
    Inicio inicio;
    Ayuda ayuda;
    Configuracion config;
    Seleccion selec;
    Dorothy dorothy;
    CardLayout cl;
    public Lienzo() {
        initComponents();
        cl = (CardLayout)this.getLayout();
    }
    public void setFrame (VentanaDesarrollo frame){
        this.frame = frame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inicio = new javax.swing.JPanel();
        tittle = new javax.swing.JLabel();
        IrAyuda = new javax.swing.JButton();
        IrConfiguracion = new javax.swing.JButton();
        IrSeleccion = new javax.swing.JButton();
        BCK1 = new javax.swing.JLabel();
        Ayuda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VolverInicio = new javax.swing.JButton();
        Configuracion = new javax.swing.JPanel();
        VolvInicio = new javax.swing.JButton();
        BCK3 = new javax.swing.JLabel();
        Seleccion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IrDorothy = new javax.swing.JButton();
        IrKatherin = new javax.swing.JButton();
        VolInicio = new javax.swing.JButton();
        IrMary = new javax.swing.JButton();
        BCK4 = new javax.swing.JLabel();
        HistoriaKatherin = new javax.swing.JPanel();
        HistoriaMary = new javax.swing.JPanel();
        HistoriaDorothy = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Inicio1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Ayuda1 = new javax.swing.JPanel();
        Configuracion1 = new javax.swing.JPanel();
        Seleccion1 = new javax.swing.JPanel();
        HistoriaKatherin1 = new javax.swing.JPanel();
        HistoriaMary1 = new javax.swing.JPanel();
        HistoriaDorothy1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Inicio2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Ayuda2 = new javax.swing.JPanel();
        Configuracion2 = new javax.swing.JPanel();
        Seleccion2 = new javax.swing.JPanel();
        HistoriaKatherin2 = new javax.swing.JPanel();
        HistoriaMary2 = new javax.swing.JPanel();
        HistoriaDorothy2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Inicio3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        Ayuda3 = new javax.swing.JPanel();
        Configuracion3 = new javax.swing.JPanel();
        Seleccion3 = new javax.swing.JPanel();
        HistoriaKatherin3 = new javax.swing.JPanel();
        HistoriaMary3 = new javax.swing.JPanel();
        HistoriaDorothy3 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1400, 800));
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setLayout(new java.awt.CardLayout());

        Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/EstellarG.png"))); // NOI18N
        Inicio.add(tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        IrAyuda.setBackground(java.awt.SystemColor.text);
        IrAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b5.png"))); // NOI18N
        IrAyuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        IrAyuda.setContentAreaFilled(false);
        IrAyuda.setMaximumSize(new java.awt.Dimension(320, 270));
        IrAyuda.setMinimumSize(new java.awt.Dimension(320, 270));
        IrAyuda.setPreferredSize(new java.awt.Dimension(320, 270));
        IrAyuda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b5-P.png"))); // NOI18N
        IrAyuda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b5-S.png"))); // NOI18N
        IrAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrAyudaActionPerformed(evt);
            }
        });
        Inicio.add(IrAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 340, 300));

        IrConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b7.png"))); // NOI18N
        IrConfiguracion.setContentAreaFilled(false);
        IrConfiguracion.setMaximumSize(new java.awt.Dimension(340, 283));
        IrConfiguracion.setMinimumSize(new java.awt.Dimension(340, 283));
        IrConfiguracion.setPreferredSize(new java.awt.Dimension(340, 283));
        IrConfiguracion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b7_P.png"))); // NOI18N
        IrConfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b7-S.png"))); // NOI18N
        IrConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrConfiguracionActionPerformed(evt);
            }
        });
        Inicio.add(IrConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, -1, -1));

        IrSeleccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b6.png"))); // NOI18N
        IrSeleccion.setContentAreaFilled(false);
        IrSeleccion.setMaximumSize(new java.awt.Dimension(320, 257));
        IrSeleccion.setMinimumSize(new java.awt.Dimension(320, 257));
        IrSeleccion.setPreferredSize(new java.awt.Dimension(320, 257));
        IrSeleccion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b6-P.png"))); // NOI18N
        IrSeleccion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b6_S.png"))); // NOI18N
        IrSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrSeleccionActionPerformed(evt);
            }
        });
        Inicio.add(IrSeleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        BCK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/InicioE.png"))); // NOI18N
        Inicio.add(BCK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(Inicio, "INICIO");

        jLabel1.setText("Ayuda");

        VolverInicio.setText("Volver a Inicio");
        VolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AyudaLayout = new javax.swing.GroupLayout(Ayuda);
        Ayuda.setLayout(AyudaLayout);
        AyudaLayout.setHorizontalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AyudaLayout.createSequentialGroup()
                .addGroup(AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AyudaLayout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(jLabel1))
                    .addGroup(AyudaLayout.createSequentialGroup()
                        .addGap(495, 495, 495)
                        .addComponent(VolverInicio)))
                .addContainerGap(792, Short.MAX_VALUE))
        );
        AyudaLayout.setVerticalGroup(
            AyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AyudaLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel1)
                .addGap(192, 192, 192)
                .addComponent(VolverInicio)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        add(Ayuda, "AYUDA");

        Configuracion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VolvInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b12.png"))); // NOI18N
        VolvInicio.setContentAreaFilled(false);
        VolvInicio.setMaximumSize(new java.awt.Dimension(110, 79));
        VolvInicio.setMinimumSize(new java.awt.Dimension(110, 79));
        VolvInicio.setPreferredSize(new java.awt.Dimension(110, 79));
        VolvInicio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b12-P.png"))); // NOI18N
        VolvInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b12-S.png"))); // NOI18N
        VolvInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolvInicioActionPerformed(evt);
            }
        });
        Configuracion.add(VolvInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        BCK3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/configE.png"))); // NOI18N
        Configuracion.add(BCK3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(Configuracion, "CONFIG");
        Configuracion.getAccessibleContext().setAccessibleName("");

        Seleccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/EstellarG.png"))); // NOI18N
        Seleccion.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        IrDorothy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b2-Invalid.png"))); // NOI18N
        IrDorothy.setContentAreaFilled(false);
        IrDorothy.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b2-Invalid-S.png"))); // NOI18N
        Seleccion.add(IrDorothy, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, -1, 350));

        IrKatherin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b3.png"))); // NOI18N
        IrKatherin.setContentAreaFilled(false);
        IrKatherin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b3-P.png"))); // NOI18N
        IrKatherin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b3-S.png"))); // NOI18N
        Seleccion.add(IrKatherin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 330));

        VolInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b12.png"))); // NOI18N
        VolInicio.setContentAreaFilled(false);
        VolInicio.setMaximumSize(new java.awt.Dimension(110, 79));
        VolInicio.setMinimumSize(new java.awt.Dimension(110, 79));
        VolInicio.setPreferredSize(new java.awt.Dimension(110, 79));
        VolInicio.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b12-P.png"))); // NOI18N
        VolInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b12-S.png"))); // NOI18N
        VolInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolInicioActionPerformed(evt);
            }
        });
        Seleccion.add(VolInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        IrMary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b1-Invalid.png"))); // NOI18N
        IrMary.setContentAreaFilled(false);
        IrMary.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/b1-Invalid-S.png"))); // NOI18N
        Seleccion.add(IrMary, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 330));

        BCK4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/SeleccionE.png"))); // NOI18N
        Seleccion.add(BCK4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(Seleccion, "SELECCION");

        javax.swing.GroupLayout HistoriaKatherinLayout = new javax.swing.GroupLayout(HistoriaKatherin);
        HistoriaKatherin.setLayout(HistoriaKatherinLayout);
        HistoriaKatherinLayout.setHorizontalGroup(
            HistoriaKatherinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaKatherinLayout.setVerticalGroup(
            HistoriaKatherinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        add(HistoriaKatherin, "HISK");

        javax.swing.GroupLayout HistoriaMaryLayout = new javax.swing.GroupLayout(HistoriaMary);
        HistoriaMary.setLayout(HistoriaMaryLayout);
        HistoriaMaryLayout.setHorizontalGroup(
            HistoriaMaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaMaryLayout.setVerticalGroup(
            HistoriaMaryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        add(HistoriaMary, "HISM");

        javax.swing.GroupLayout HistoriaDorothyLayout = new javax.swing.GroupLayout(HistoriaDorothy);
        HistoriaDorothy.setLayout(HistoriaDorothyLayout);
        HistoriaDorothyLayout.setHorizontalGroup(
            HistoriaDorothyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaDorothyLayout.setVerticalGroup(
            HistoriaDorothyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        add(HistoriaDorothy, "HISD");

        jPanel1.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel1.setLayout(new java.awt.CardLayout());

        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inicio1Layout = new javax.swing.GroupLayout(Inicio1);
        Inicio1.setLayout(Inicio1Layout);
        Inicio1Layout.setHorizontalGroup(
            Inicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio1Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jButton2)
                .addContainerGap(883, Short.MAX_VALUE))
        );
        Inicio1Layout.setVerticalGroup(
            Inicio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jButton2)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jPanel1.add(Inicio1, "INICIO");

        javax.swing.GroupLayout Ayuda1Layout = new javax.swing.GroupLayout(Ayuda1);
        Ayuda1.setLayout(Ayuda1Layout);
        Ayuda1Layout.setHorizontalGroup(
            Ayuda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Ayuda1Layout.setVerticalGroup(
            Ayuda1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel1.add(Ayuda1, "AYUDA");

        javax.swing.GroupLayout Configuracion1Layout = new javax.swing.GroupLayout(Configuracion1);
        Configuracion1.setLayout(Configuracion1Layout);
        Configuracion1Layout.setHorizontalGroup(
            Configuracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Configuracion1Layout.setVerticalGroup(
            Configuracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel1.add(Configuracion1, "CONFIG");

        javax.swing.GroupLayout Seleccion1Layout = new javax.swing.GroupLayout(Seleccion1);
        Seleccion1.setLayout(Seleccion1Layout);
        Seleccion1Layout.setHorizontalGroup(
            Seleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Seleccion1Layout.setVerticalGroup(
            Seleccion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel1.add(Seleccion1, "SELECCION");

        javax.swing.GroupLayout HistoriaKatherin1Layout = new javax.swing.GroupLayout(HistoriaKatherin1);
        HistoriaKatherin1.setLayout(HistoriaKatherin1Layout);
        HistoriaKatherin1Layout.setHorizontalGroup(
            HistoriaKatherin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaKatherin1Layout.setVerticalGroup(
            HistoriaKatherin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel1.add(HistoriaKatherin1, "HISK");

        javax.swing.GroupLayout HistoriaMary1Layout = new javax.swing.GroupLayout(HistoriaMary1);
        HistoriaMary1.setLayout(HistoriaMary1Layout);
        HistoriaMary1Layout.setHorizontalGroup(
            HistoriaMary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaMary1Layout.setVerticalGroup(
            HistoriaMary1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel1.add(HistoriaMary1, "HISM");

        javax.swing.GroupLayout HistoriaDorothy1Layout = new javax.swing.GroupLayout(HistoriaDorothy1);
        HistoriaDorothy1.setLayout(HistoriaDorothy1Layout);
        HistoriaDorothy1Layout.setHorizontalGroup(
            HistoriaDorothy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaDorothy1Layout.setVerticalGroup(
            HistoriaDorothy1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel1.add(HistoriaDorothy1, "HISD");

        add(jPanel1, "card9");

        jPanel2.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel2.setLayout(new java.awt.CardLayout());

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inicio2Layout = new javax.swing.GroupLayout(Inicio2);
        Inicio2.setLayout(Inicio2Layout);
        Inicio2Layout.setHorizontalGroup(
            Inicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio2Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jButton3)
                .addContainerGap(883, Short.MAX_VALUE))
        );
        Inicio2Layout.setVerticalGroup(
            Inicio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio2Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jButton3)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jPanel2.add(Inicio2, "INICIO");

        javax.swing.GroupLayout Ayuda2Layout = new javax.swing.GroupLayout(Ayuda2);
        Ayuda2.setLayout(Ayuda2Layout);
        Ayuda2Layout.setHorizontalGroup(
            Ayuda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Ayuda2Layout.setVerticalGroup(
            Ayuda2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(Ayuda2, "AYUDA");

        javax.swing.GroupLayout Configuracion2Layout = new javax.swing.GroupLayout(Configuracion2);
        Configuracion2.setLayout(Configuracion2Layout);
        Configuracion2Layout.setHorizontalGroup(
            Configuracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Configuracion2Layout.setVerticalGroup(
            Configuracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(Configuracion2, "CONFIG");

        javax.swing.GroupLayout Seleccion2Layout = new javax.swing.GroupLayout(Seleccion2);
        Seleccion2.setLayout(Seleccion2Layout);
        Seleccion2Layout.setHorizontalGroup(
            Seleccion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Seleccion2Layout.setVerticalGroup(
            Seleccion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(Seleccion2, "SELECCION");

        javax.swing.GroupLayout HistoriaKatherin2Layout = new javax.swing.GroupLayout(HistoriaKatherin2);
        HistoriaKatherin2.setLayout(HistoriaKatherin2Layout);
        HistoriaKatherin2Layout.setHorizontalGroup(
            HistoriaKatherin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaKatherin2Layout.setVerticalGroup(
            HistoriaKatherin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(HistoriaKatherin2, "HISK");

        javax.swing.GroupLayout HistoriaMary2Layout = new javax.swing.GroupLayout(HistoriaMary2);
        HistoriaMary2.setLayout(HistoriaMary2Layout);
        HistoriaMary2Layout.setHorizontalGroup(
            HistoriaMary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaMary2Layout.setVerticalGroup(
            HistoriaMary2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(HistoriaMary2, "HISM");

        javax.swing.GroupLayout HistoriaDorothy2Layout = new javax.swing.GroupLayout(HistoriaDorothy2);
        HistoriaDorothy2.setLayout(HistoriaDorothy2Layout);
        HistoriaDorothy2Layout.setHorizontalGroup(
            HistoriaDorothy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaDorothy2Layout.setVerticalGroup(
            HistoriaDorothy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel2.add(HistoriaDorothy2, "HISD");

        jPanel3.setMaximumSize(new java.awt.Dimension(1400, 800));
        jPanel3.setMinimumSize(new java.awt.Dimension(1400, 800));
        jPanel3.setLayout(new java.awt.CardLayout());

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Inicio3Layout = new javax.swing.GroupLayout(Inicio3);
        Inicio3.setLayout(Inicio3Layout);
        Inicio3Layout.setHorizontalGroup(
            Inicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio3Layout.createSequentialGroup()
                .addGap(438, 438, 438)
                .addComponent(jButton4)
                .addContainerGap(883, Short.MAX_VALUE))
        );
        Inicio3Layout.setVerticalGroup(
            Inicio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Inicio3Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jButton4)
                .addContainerGap(449, Short.MAX_VALUE))
        );

        jPanel3.add(Inicio3, "INICIO");

        javax.swing.GroupLayout Ayuda3Layout = new javax.swing.GroupLayout(Ayuda3);
        Ayuda3.setLayout(Ayuda3Layout);
        Ayuda3Layout.setHorizontalGroup(
            Ayuda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Ayuda3Layout.setVerticalGroup(
            Ayuda3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(Ayuda3, "AYUDA");

        javax.swing.GroupLayout Configuracion3Layout = new javax.swing.GroupLayout(Configuracion3);
        Configuracion3.setLayout(Configuracion3Layout);
        Configuracion3Layout.setHorizontalGroup(
            Configuracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Configuracion3Layout.setVerticalGroup(
            Configuracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(Configuracion3, "CONFIG");

        javax.swing.GroupLayout Seleccion3Layout = new javax.swing.GroupLayout(Seleccion3);
        Seleccion3.setLayout(Seleccion3Layout);
        Seleccion3Layout.setHorizontalGroup(
            Seleccion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        Seleccion3Layout.setVerticalGroup(
            Seleccion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(Seleccion3, "SELECCION");

        javax.swing.GroupLayout HistoriaKatherin3Layout = new javax.swing.GroupLayout(HistoriaKatherin3);
        HistoriaKatherin3.setLayout(HistoriaKatherin3Layout);
        HistoriaKatherin3Layout.setHorizontalGroup(
            HistoriaKatherin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaKatherin3Layout.setVerticalGroup(
            HistoriaKatherin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(HistoriaKatherin3, "HISK");

        javax.swing.GroupLayout HistoriaMary3Layout = new javax.swing.GroupLayout(HistoriaMary3);
        HistoriaMary3.setLayout(HistoriaMary3Layout);
        HistoriaMary3Layout.setHorizontalGroup(
            HistoriaMary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaMary3Layout.setVerticalGroup(
            HistoriaMary3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(HistoriaMary3, "HISM");

        javax.swing.GroupLayout HistoriaDorothy3Layout = new javax.swing.GroupLayout(HistoriaDorothy3);
        HistoriaDorothy3.setLayout(HistoriaDorothy3Layout);
        HistoriaDorothy3Layout.setHorizontalGroup(
            HistoriaDorothy3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        HistoriaDorothy3Layout.setVerticalGroup(
            HistoriaDorothy3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        jPanel3.add(HistoriaDorothy3, "HISD");

        jPanel2.add(jPanel3, "card9");

        add(jPanel2, "card10");
    }// </editor-fold>//GEN-END:initComponents

    private void IrAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrAyudaActionPerformed
        cl.show(this, "AYUDA");
    }//GEN-LAST:event_IrAyudaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void IrConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrConfiguracionActionPerformed
        cl.show(this, "CONFIG");
    }//GEN-LAST:event_IrConfiguracionActionPerformed

    private void VolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverInicioActionPerformed
        cl.show(this, "INICIO");
    }//GEN-LAST:event_VolverInicioActionPerformed

    private void VolvInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolvInicioActionPerformed
        cl.show(this, "INICIO");
    }//GEN-LAST:event_VolvInicioActionPerformed

    private void IrSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrSeleccionActionPerformed
        cl.show(this, "SELECCION");
    }//GEN-LAST:event_IrSeleccionActionPerformed

    private void VolInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolInicioActionPerformed
        cl.show(this, "INICIO");
    }//GEN-LAST:event_VolInicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Ayuda;
    private javax.swing.JPanel Ayuda1;
    private javax.swing.JPanel Ayuda2;
    private javax.swing.JPanel Ayuda3;
    private javax.swing.JLabel BCK1;
    private javax.swing.JLabel BCK3;
    private javax.swing.JLabel BCK4;
    private javax.swing.JPanel Configuracion;
    private javax.swing.JPanel Configuracion1;
    private javax.swing.JPanel Configuracion2;
    private javax.swing.JPanel Configuracion3;
    private javax.swing.JPanel HistoriaDorothy;
    private javax.swing.JPanel HistoriaDorothy1;
    private javax.swing.JPanel HistoriaDorothy2;
    private javax.swing.JPanel HistoriaDorothy3;
    private javax.swing.JPanel HistoriaKatherin;
    private javax.swing.JPanel HistoriaKatherin1;
    private javax.swing.JPanel HistoriaKatherin2;
    private javax.swing.JPanel HistoriaKatherin3;
    private javax.swing.JPanel HistoriaMary;
    private javax.swing.JPanel HistoriaMary1;
    private javax.swing.JPanel HistoriaMary2;
    private javax.swing.JPanel HistoriaMary3;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Inicio1;
    private javax.swing.JPanel Inicio2;
    private javax.swing.JPanel Inicio3;
    private javax.swing.JButton IrAyuda;
    private javax.swing.JButton IrConfiguracion;
    private javax.swing.JButton IrDorothy;
    private javax.swing.JButton IrKatherin;
    private javax.swing.JButton IrMary;
    private javax.swing.JButton IrSeleccion;
    private javax.swing.JPanel Seleccion;
    private javax.swing.JPanel Seleccion1;
    private javax.swing.JPanel Seleccion2;
    private javax.swing.JPanel Seleccion3;
    private javax.swing.JButton VolInicio;
    private javax.swing.JButton VolvInicio;
    private javax.swing.JButton VolverInicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel tittle;
    // End of variables declaration//GEN-END:variables
}
