/*00
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/**
 *
 * @author Administrador
 */
public class PathFinder extends javax.swing.JFrame {

    private Background fondo;
    private HistoriaKatherin histK;
    static int cont = 1;
    private int i = 0;
    private int stop = 1;
    private int limiteT = 120;
    private int tiempo = 0;
    private int c = 0;

    public PathFinder(HistoriaKatherin histK, Boolean win) {

        initComponents();
        setLocationRelativeTo(null);
        setTitle("Juego Puzzle");
        btn9.setVisible(false);
        txttiempo.setEnabled(false);
        txtmovimiento.setEnabled(false);
        conti.setVisible(false);
        this.Win.setVisible(false);
        this.histK = histK;
        pausa.setVisible(false);
        hilo1.start();
        hilo2.start();
        reiniciar.setVisible(false);
        fondo = new Background(getWidth(), getHeight());
        setResizable(false);
        add(fondo, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NumMov = new javax.swing.JLabel();
        txtmovimiento = new javax.swing.JTextField();
        TimeG = new javax.swing.JLabel();
        txttiempo = new javax.swing.JTextField();
        pausa = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        comenzar = new javax.swing.JButton();
        conti = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        Win = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(165, 205, 235));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NumMov.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        NumMov.setText("Numero de movimientos");
        jPanel2.add(NumMov, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtmovimiento.setText("0");
        jPanel2.add(txtmovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 69, -1));

        TimeG.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        TimeG.setText("Tiempo de juego");
        jPanel2.add(TimeG, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        txttiempo.setText("0");
        jPanel2.add(txttiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 131, 60));

        pausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/pause.png"))); // NOI18N
        pausa.setBorder(null);
        pausa.setContentAreaFilled(false);
        pausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausaActionPerformed(evt);
            }
        });
        jPanel2.add(pausa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 40, 40));

        reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/reset.png"))); // NOI18N
        reiniciar.setBorder(null);
        reiniciar.setContentAreaFilled(false);
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });
        jPanel2.add(reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        comenzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/play.png"))); // NOI18N
        comenzar.setBorder(null);
        comenzar.setContentAreaFilled(false);
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });
        jPanel2.add(comenzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 70));

        conti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/Continuar.png"))); // NOI18N
        conti.setContentAreaFilled(false);
        conti.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/Continuar-P.png"))); // NOI18N
        conti.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/Continuar-S.png"))); // NOI18N
        conti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contiActionPerformed(evt);
            }
        });
        jPanel2.add(conti, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 100, -1));

        jPanel3.setBackground(new java.awt.Color(165, 205, 235));
        jPanel3.setLayout(new java.awt.GridLayout(3, 3));

        btn1.setBackground(new java.awt.Color(153, 153, 255));
        btn1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("1");
        btn1.setBorder(null);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn1);

        btn2.setBackground(new java.awt.Color(153, 153, 255));
        btn2.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn2.setForeground(new java.awt.Color(255, 255, 255));
        btn2.setText("2");
        btn2.setBorder(null);
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel3.add(btn2);

        btn3.setBackground(new java.awt.Color(153, 153, 255));
        btn3.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn3.setForeground(new java.awt.Color(255, 255, 255));
        btn3.setText("3");
        btn3.setBorder(null);
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel3.add(btn3);

        btn4.setBackground(new java.awt.Color(153, 153, 255));
        btn4.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn4.setForeground(new java.awt.Color(255, 255, 255));
        btn4.setText("4");
        btn4.setBorder(null);
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel3.add(btn4);

        btn5.setBackground(new java.awt.Color(153, 153, 255));
        btn5.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn5.setForeground(new java.awt.Color(255, 255, 255));
        btn5.setText("5");
        btn5.setBorder(null);
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel3.add(btn5);

        btn6.setBackground(new java.awt.Color(153, 153, 255));
        btn6.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn6.setForeground(new java.awt.Color(255, 255, 255));
        btn6.setText("6");
        btn6.setBorder(null);
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel3.add(btn6);

        btn7.setBackground(new java.awt.Color(153, 153, 255));
        btn7.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn7.setForeground(new java.awt.Color(255, 255, 255));
        btn7.setText("7");
        btn7.setBorder(null);
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel3.add(btn7);

        btn8.setBackground(new java.awt.Color(153, 153, 255));
        btn8.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn8.setForeground(new java.awt.Color(255, 255, 255));
        btn8.setText("8");
        btn8.setBorder(null);
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel3.add(btn8);

        btn9.setBackground(new java.awt.Color(153, 153, 255));
        btn9.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        btn9.setForeground(new java.awt.Color(255, 255, 255));
        btn9.setText("9");
        btn9.setBorder(null);
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel3.add(btn9);

        Win.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Images/PathFinder/felicidades.png"))); // NOI18N
        Win.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Win, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Win))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  Thread hilo1 = new Thread() {
        @Override
        public void run() {
            int infinito = 0;

            while (infinito == 0) {
                try {
                    
                    if (stop == 0 && c > 11) {
                        txttiempo.setText(String.valueOf(tiempo++));
                    }
                    Thread.sleep(1000);
                } catch (InterruptedException e) {

                }
            }
        }
    };

    Thread hilo2 = new Thread() {
        @Override
        public void run() {
            int z = 0;
            while (z == 0) {
                try {
                    if (stop == 0) {
                        c++;
                    }
                    if (stop == 0 && c > 5) {
                        ganar();
                    }
                    
                    if (tiempo ==31){
                        stop = 1;
                        pausa.setVisible(false);
                        reiniciar.setVisible(true);
                    }
                    if (c == 1) {
                        btn1.setEnabled(false);
                        btn2.setEnabled(false);
                        btn3.setEnabled(false);
                        btn4.setEnabled(false);
                        btn5.setEnabled(false);
                        btn6.setEnabled(false);
                        btn7.setEnabled(false);
                        btn8.setEnabled(false);
                        btn9.setEnabled(false);
                    }

                    if (c == 2) {
                        movimiento(btn9, btn6);
                    }
                    if (c == 3) {
                        movimiento(btn6, btn3);
                    }
                    if (c == 4) {
                        movimiento(btn3, btn2);
                    }
                    if (c == 5) {
                        movimiento(btn2, btn5);
                    }
                    if (c == 6) {
                        movimiento(btn5, btn4);
                    }
                    if (c == 7) {
                        movimiento(btn4, btn7);
                    }
                    if (c == 8) {
                        movimiento(btn7, btn8);
                    }
                    if (c == 9) {
                        movimiento(btn8, btn5);
                    }
                    if (c == 10) {
                        movimiento(btn5, btn6);
                    }
                    if (c == 11) {
                        movimiento(btn6, btn3);
                    }
                    if (c == 12) {
                        movimiento(btn3, btn2);
                    }
                    if (c == 13) {
                        movimiento(btn2, btn1);
                        btn1.setEnabled(true);
                        btn2.setEnabled(true);
                        btn3.setEnabled(true);
                        btn4.setEnabled(true);
                        btn5.setEnabled(true);
                        btn6.setEnabled(true);
                        btn7.setEnabled(true);
                        btn8.setEnabled(true);
                        btn9.setEnabled(true);

                    }

                    Thread.sleep(300);
                } catch (InterruptedException e) {

                }
            }
        }
    };

    public void ordenar() {
        btn1.setVisible(true);
        btn2.setVisible(true);
        btn3.setVisible(true);
        btn4.setVisible(true);
        btn5.setVisible(true);
        btn6.setVisible(true);
        btn7.setVisible(true);
        btn8.setVisible(true);
        btn9.setVisible(false);
        btn1.setText(String.valueOf(1));
        btn2.setText(String.valueOf(2));
        btn3.setText(String.valueOf(3));
        btn4.setText(String.valueOf(4));
        btn5.setText(String.valueOf(5));
        btn6.setText(String.valueOf(6));
        btn7.setText(String.valueOf(7));
        btn8.setText(String.valueOf(8));
        c = 0;

    }
    //probar

    private void contarMovimiento() {
        if (c > 13) {
            txtmovimiento.setText(String.valueOf(cont++));
        }
    }
    //probar

    private void ganar() {
        if (Integer.parseInt(btn1.getText()) == 1) {
            if (Integer.parseInt(btn2.getText()) == 2) {
                if (Integer.parseInt(btn3.getText()) == 3) {
                    if (Integer.parseInt(btn4.getText()) == 4) {
                        if (Integer.parseInt(btn5.getText()) == 5) {
                            if (Integer.parseInt(btn6.getText()) == 6) {
                                if (Integer.parseInt(btn7.getText()) == 7) {
                                    if (Integer.parseInt(btn8.getText()) == 8) {
                                        Win.setVisible(true);
                                        stop = 1;
                                        pausa.setVisible(false);
                                        reiniciar.setVisible(true);
                                        conti.setVisible(true);
                                        histK.setWin(0, true);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    //probbar

    private void empezar() {
        stop = 0;
        if (c == 0) {
            ordenar();
            Win.setVisible(false);
        }
        comenzar.setVisible(false);
        reiniciar.setVisible(false);
        pausa.setVisible(true);

    }

    //probar
    private void pausa() {
        stop = 1;

        pausa.setVisible(false);
        comenzar.setVisible(true);
        reiniciar.setVisible(true);
    }

    //probar
    private void reiniciar() {
        pausa();
        tiempo = 0;
        cont = 0;
        c = 0;
        txtmovimiento.setText(String.valueOf(cont));
        txttiempo.setText(String.valueOf(tiempo));
        reiniciar.setVisible(false);
        Win.setVisible(false);

    }

    public void movimiento(JButton b1, JButton b2) {

        b1.setText(b2.getText());
        b1.setIcon(b2.getIcon());
        b2.setVisible(false);
        b1.setVisible(true);
        contarMovimiento();
    }
    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if (stop == 0) {
            if (btn2.isVisible() == false) {
                movimiento(btn2, btn3);
            }
            if (btn6.isVisible() == false) {
                movimiento(btn6, btn3);
            }
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if (stop == 0) {
            if (btn2.isVisible() == false) {
                movimiento(btn2, btn5);
            }
            if (btn4.isVisible() == false) {
                movimiento(btn4, btn5);
            }
            if (btn8.isVisible() == false) {
                movimiento(btn8, btn5);
            }
            if (btn6.isVisible() == false) {
                movimiento(btn6, btn5);
            }
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if (stop == 0) {
            if (btn9.isVisible() == false) {
                movimiento(btn9, btn6);
            }
            if (btn3.isVisible() == false) {
                movimiento(btn3, btn6);
            }
            if (btn5.isVisible() == false) {
                movimiento(btn5, btn6);
            }
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if (stop == 0) {
            if (btn6.isVisible() == false) {
                movimiento(btn6, btn9);
            }
            if (btn8.isVisible() == false) {
                movimiento(btn8, btn9);
            }
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if (stop == 0) {
            if (btn3.isVisible() == false) {
                movimiento(btn3, btn2);
            }
            if (btn1.isVisible() == false) {
                movimiento(btn1, btn2);
            }
            if (btn5.isVisible() == false) {
                movimiento(btn5, btn2);
            }
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if (stop == 0) {
            if (btn7.isVisible() == false) {
                movimiento(btn7, btn8);
            }
            if (btn9.isVisible() == false) {
                movimiento(btn9, btn8);
            }
            if (btn5.isVisible() == false) {
                movimiento(btn5, btn8);
            }
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if (stop == 0) {
            if (btn4.isVisible() == false) {
                movimiento(btn4, btn7);
            }
            if (btn8.isVisible() == false) {
                movimiento(btn8, btn7);
            }
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if (stop == 0) {
            if (btn1.isVisible() == false) {
                movimiento(btn1, btn4);
            }
            if (btn5.isVisible() == false) {
                movimiento(btn5, btn4);
            }
            if (btn7.isVisible() == false) {
                movimiento(btn7, btn4);
            }
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (stop == 0) {
            if (btn2.isVisible() == false) {
                movimiento(btn2, btn1);
            }
            if (btn4.isVisible() == false) {
                movimiento(btn4, btn1);
            }
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
        empezar();
    }//GEN-LAST:event_comenzarActionPerformed

    private void pausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausaActionPerformed
        pausa();
    }//GEN-LAST:event_pausaActionPerformed

    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_reiniciarActionPerformed

    private void contiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contiActionPerformed
        dispose();
    }//GEN-LAST:event_contiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NumMov;
    private javax.swing.JLabel TimeG;
    private javax.swing.JLabel Win;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton comenzar;
    private javax.swing.JButton conti;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    private javax.swing.JButton pausa;
    private javax.swing.JButton reiniciar;
    private javax.swing.JTextField txtmovimiento;
    private javax.swing.JTextField txttiempo;
    // End of variables declaration//GEN-END:variables
}
